apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sit722part3.azurecr.io/book-catalog:1
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "8081"
        - name: DATABASE_URL
          value: "postgresql://week08_huk2_user:mGnWfRNxlYute14AaDRRhcDkJzzGHmOb@dpg-crn4gj56l47c73a9fb0g-a.oregon-postgres.render.com/week08_huk2"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  type: LoadBalancer
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: sit722part3.azurecr.io/inventory-management:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "8082"
        - name: DATABASE_URL
          value: "postgresql://week08_huk2_user:mGnWfRNxlYute14AaDRRhcDkJzzGHmOb@dpg-crn4gj56l47c73a9fb0g-a.oregon-postgres.render.com/week08_huk2"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  type: LoadBalancer
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
